package lt.insoft.cpr2epolicija.model.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-05-02T12:43:19.816+03:00
 * Generated source version: 3.1.12
 *
 */
@WebService(targetNamespace = "http://ws.s2s.eservices.insoft.lt/", name = "S2sService")
@XmlSeeAlso({ObjectFactory.class})
public interface S2SService {

    @WebMethod
    @RequestWrapper(localName = "sendReport", targetNamespace = "http://ws.s2s.eservices.insoft.lt/", className = "lt.insoft.cpr2epolicija.model.ws.SendReport")
    @ResponseWrapper(localName = "sendReportResponse", targetNamespace = "http://ws.s2s.eservices.insoft.lt/", className = "lt.insoft.cpr2epolicija.model.ws.SendReportResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String sendReport(
            @WebParam(name = "senderCode", targetNamespace = "")
                    String senderCode,
            @WebParam(name = "encodedSignedReport", targetNamespace = "")
                    String encodedSignedReport) throws S2SServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getIvykisClassifier", targetNamespace = "http://ws.s2s.eservices.insoft.lt/", className = "lt.insoft.cpr2epolicija.model.ws.GetIvykisClassifier")
    @ResponseWrapper(localName = "getIvykisClassifierResponse", targetNamespace = "http://ws.s2s.eservices.insoft.lt/", className = "lt.insoft.cpr2epolicija.model.ws.GetIvykisClassifierResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<KeyValuePair> getIvykisClassifier() throws S2SServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "test", targetNamespace = "http://ws.s2s.eservices.insoft.lt/", className = "lt.insoft.cpr2epolicija.model.ws.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://ws.s2s.eservices.insoft.lt/", className = "lt.insoft.cpr2epolicija.model.ws.TestResponse")
    public void test(
            @WebParam(name = "arg0", targetNamespace = "")
                    Report arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    StatusRequest arg1);

    @WebMethod
    @RequestWrapper(localName = "getReportStatus", targetNamespace = "http://ws.s2s.eservices.insoft.lt/", className = "lt.insoft.cpr2epolicija.model.ws.GetReportStatus")
    @ResponseWrapper(localName = "getReportStatusResponse", targetNamespace = "http://ws.s2s.eservices.insoft.lt/", className = "lt.insoft.cpr2epolicija.model.ws.GetReportStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<StatusResponse> getReportStatus(
            @WebParam(name = "senderCode", targetNamespace = "")
                    String senderCode,
            @WebParam(name = "encodedSignedStatusRequest", targetNamespace = "")
                    String encodedSignedStatusRequest) throws S2SServiceException_Exception;
}
