
package lt.insoft.cpr2epolicija.model.ws;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-05-02T12:43:19.786+03:00
 * Generated source version: 3.1.12
 */

@WebFault(name = "S2sServiceException", targetNamespace = "http://ws.s2s.eservices.insoft.lt/")
public class S2SServiceException_Exception extends Exception {

    private S2SServiceException s2SServiceException;

    public S2SServiceException_Exception() {
        super();
    }

    public S2SServiceException_Exception(String message) {
        super(message);
    }

    public S2SServiceException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public S2SServiceException_Exception(String message, S2SServiceException s2SServiceException) {
        super(message);
        this.s2SServiceException = s2SServiceException;
    }

    public S2SServiceException_Exception(String message, S2SServiceException s2SServiceException, Throwable cause) {
        super(message, cause);
        this.s2SServiceException = s2SServiceException;
    }

    public S2SServiceException getFaultInfo() {
        return this.s2SServiceException;
    }
}
